= About This Course
:navtitle: Home

== Writing Targeted Policies for SELinux on Red Hat Enterprise Linux

This course teaches the development of SELinux policies that extend the Red Hat Enterprise Linux (RHEL) *targeted* policy set. It focuses on developing SELinux policies with the help of development tooling included in RHEL, especially the `sepolicy generate` and `audit2allow` commands.

== Audience

System Administrators, Site Reliability Engineers, Application Developers, and other IT professionals responsible for securing applications running on Linux servers.

== Prerequisites

Learners are expected to have experience managing RHEL servers, and are expected to have some familiarity with managing SELinux on RHEL.

If you're not new to SELinux but need a refresher on it's day-to-day administration, please review:

* The https://developers.redhat.com/courses/enhance-red-hat-enterprise-linux-selinux[Enhance RHEL with SELinux] tutorial by https://developers.redhat.com/learn[Red Hat Developers].
* The https://opensource.com/article/18/7/sysadmin-guide-selinux[The Sysadmin Guide to SELinux] by Alex Callejas

If you need an overview of SELinux, please review the following conceptual introduction:

* https://opensource.com/business/13/11/selinux-policy-guide[Your visual how-to guide for SELinux policy enforcement] by Daniel J Walsh
* https://developers.redhat.com/e-books/selinux-coloring-book[The SELinux Coloring Book] eBook by Red Hat Developers

== Classroom Environment

For now, there is no virtual labs for performing hands-on activities. You just need a RHEL server or VM to which you have root access and from which can download RPM packages from Red Hat repositories or a Yum mirror.

As course development progresses, some Red Hat Training course classroom or Red Hat Demo workshop environment will be selected as ready-to-use environments for hands-on activities.

You could even try these activities directly on your day-to-day machine or a local VM where you install RHEL.

If you do not have a test machine readily available, but you have access to a https://www.redhat.com/en/services/training/learning-subscription[Red Hat Learning Subscription] (as all Red Hat employees and partners do) you can use the virtual lab environment from https://www.redhat.com/en/services/training/rh134-red-hat-system-administration-ii[Red Hat System Administration II (RH134)]. You can use either `servera` or `serverb` machines to perform all activities in this course.

This course was tested with the RHEL 9.3 version of the RH134 classroom, but is expected to work with older and newer releases of that course classroom.

To use RH134 as your virtual lab for hands-on activities, please follow one of the following links:

* https://role.rhu.redhat.com/rol-rhu/app/courses/rh134-9.3/pages/pr01s02[RH134 for Red Hat Employees].
* https://rol.redhat.com/rol/app/courses/rh134-9.3/pages/pr01s02[RH134 for Red Hat Customers and Partners with a Learning Subscription].

== Additional Red Hat Training About SELinux

If you are new to SELinux on RHEL, you are strongly advised to start by reviewing the following content from Red Hat Training courses:

=== For Red Hat employees

* https://role.rhu.redhat.com/rol-rhu/app/courses/rh134-9.0/pages/ch06[RH134 Chapter 06]
* https://role.rhu.redhat.com/rol-rhu/app/courses/rh134-9.0/pages/ch11s03[RH134 Chapter 11] 
* https://role.rhu.redhat.com/rol-rhu/app/courses/rh415-9.2/pages/ch08[RH415 Chapter 08]
* https://role.rhu.redhat.com/rol-rhu/app/courses/rh342-8.4/pages/ch09[RH342 Chapter 09]

=== For Red Hat Customers and Partners with a Learning Subscription

* https://rol.redhat.com/rol/app/courses/rh134-9.0/pages/ch06[RH134 Chapter 6]
* https://rol.redhat.com/rol/app/courses/rh134-9.0/pages/ch11s03[RH134 Chapter 11]
* https://rol.redhat.com/rol/app/courses/rh415-9.2/pages/ch08[RH415 Chapter 8]
* https://rol.redhat.com/rol/app/courses/rh342-8.4/pages/ch09[RH342 Chapter 9]

== Other Sources of Information About SELinux

Of course, the ultimate sources of information about SELinux are the Red Hat Enterprise Linux product documentation and the upstream from the Fedora Project and the SELinux project.

* https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/using_selinux/index[Using SELinux] from the RHEL product documentation.
* https://fedoraproject.org/wiki/SELinux[SELinux - Fedora Project Wiki] as the community upstream from RHEL, provides important information on packaging.
* https://github.com/SELinuxProject/selinux-notebook[The SELinux Notebook] is te upstream documentation of the SELinux project.

== Author

*Fernando Lozano* +
Training Content Architect +
Red Hat - Product Portfolio Marketing & Learning

Based on previous work by *Lukas Vrabec* and *Paul Armstrong*. 

//Special thanks to.. for...
