:time_estimate: 5

= Interpreting AVC messages

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Assess if an SELinux access denied message can be resolved by a change of configuration, without creating a custom policy.

WARNING: Pending Review

== Title

Lorem Ipsum

=== Labeling Files With a New Context Type

You can change the context type of a file directly with the `chcon` command, but you're not adivised to. It is recommended that you define a new path expression for the intended type with the `semanage` command, and them you apply the type to the file with the `restorecon` command.

For example, the SELinux policy for the Apache Web Server defines the `httpd_sys_content_t` type for web pages. If you create a virtual host with a document root somewhere else, you must label that directory with the `httpd_sys_content_t` type.

Another example, the SELinux policy for MySQL defines the `mysqld_port_t` type for the standard MySQL server port 3306. If you configure a second instance of the MySQL daemon, you must add its TCP port to the SELinux policy with the the `mysqld_port_t` type.

=== Setting SELinux Booleans

The SELinux policies from RHEL define a number of booleans, which enabe system administrators to selectively grant permission to use enable features of system services. If you enable the feature in the service's configuration file but do not enable the boolean, SELinux will not allow the service to perform the intended action.

Booleans provide a compromise between a too script policy, which becomes unusable, and a too lenient policy, which leaves too large an attach surface.

For example, the Apache We Server could just serve static web pages, but it also could serve dynamic pages which access databases, send e-mail, and perform a number of other tasks using it Apache modules and scripting languages such as PHP. To use those features, you must enable booleans such as `httpd_can_network_connect_db` and `httpd_can_sendmail`.



== FROM HERE ON, RAW COPY-AND-PASTE FROM OTHER SOURCES, PENDING REORGANIZATION

https://docs.google.com/presentation/d/11K6ykCk2d9QySZ3rVzJWnX6FADEGLCacVAmumbBlENs/edit#

=== Audit logs, ausearch, audit2allow: slides #94-104

AVC MESSAGES

WHERE CAN WE FIND LOGS? 

[source,subs="verbatim,quotes"]
--
# cat /var/log/audit/audit.log
# ausearch -m AVC
--

type=AVC msg=audit(1226882925.714:136): avc:  denied  { read } for  pid=2512 comm="httpd" name="file1" dev=dm-0 ino=284133 scontext=unconfined_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:shadow_t:s0 tclass=file

AUDITD.SERVICE HAVE TO BE RUNNING

HOW TO PARSE AVC MESSAGES?

[source,subs="verbatim,quotes"]
--
# ausearch
# audit2allow
--

[source,subs="verbatim,quotes"]
--
# ausearch -m AVC -ts recent
type=AVC msg=audit(1226882925.714:136): avc:  denied  { read } for  pid=2512 comm="httpd" name="shadow" dev=dm-0 ino=284133 scontext=unconfined_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:shadow_t:s0 tclass=file
# ausearch -m AVC -ts recent | audit2allow
#============= httpd_t ==============
allow httpd_t shadow_t:file read;
--

[source,subs="verbatim,quotes"]
--
# semanage fcontext -> manage SELinux contexts
# semanage boolean -> manage SELinux booleans
# semanage port -> manage SELinux ports
# semanage permissive -> put SELinux domain to permissive mode
# sesearch -> search for present SELinux rules
# ausearch -> search for SELinux denials
# sealert -> SELinux troubleshooter
# audit2allow -> Parse SELinux denials / create local SELinux module
# semodule -DB / # semodule -B -> SELinux policy rebuild
--
