:time_estimate: 5

= Supporting SELinux

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Adopt a structured workflow for resolving SELinux issues.

WARNING: Pending Review

== Common Issues With SELinux

As you learned in the previous chapter, the SELinux targeted policy in RHEL was designed to protect system services included with RHEL and not interfere with interactive users nor with third-party applications. By design, you should be able to resolve most common issues without resorting to creating a custom policy module.

You also learned that, if you add a third-party application to a RHEL server, it's better that you, its developer, or its vendor provides a custom policy module to protect that third-party application. But you don't have to: it is recommended but optional.

Why people stil struggle with runing Linux servers with SELinux enabled and in enforcing mode? Most of the times, it's because they did one of those common things:

* Moved files around, so their SELinux context do not match the policy rules anymore.

* Restored files from a backup tool, remote file share, or removable media that does not support extended attributes, so the SELinux context of those files was lost.

* Configured a system server to listen on a non-standard network port, and that port is not labeled to match the policy rules.

* Configured a system server to read or write to different data and log directories, and those directories do not have labels which match the policy rules.

* Enabled an optional feature of a system service that is potentialy dangerouns so it's not allowed by default policy rules.

You resolve most of those isues by setting files and directories to the correct SELinux context, and the latest issue you resolve by setting an SELinux boolean.

== Labeling Files With a New Context

You can change the context type of a file directly with the `chcon` command, but you're not adivised to. It is recommended that you define a new path expression for the intended type with the `semanage` command, and them you apply the type to the file with the `restorecon` command.

For example, the SELinux policy for the Apache Web Server defines the `httpd_sys_content_t` type for web pages. If you create a virtual host with a document root somewhere else, you must label that directory with the `httpd_sys_content_t` type.

== Labeling Non-file Resources

To label other classes of kernel objects, which cannot store the labels in extended attributes, you must use the `semanage` command. For example, use `semanage port` to label TCP and UDP ports.

For example, the SELinux policy for MySQL defines the `mysqld_port_t` type for the standard MySQL server port 3306. If you configure a second instance of the MySQL daemon, you must add its TCP port to the SELinux policy with the the `mysqld_port_t` type.

== Setting SELinux Booleans

The SELinux policies from RHEL define a number of booleans, which enabe system administrators to selectively grant permission to use optional features of system services. If you enable the feature in the service's configuration file but do not enable the boolean, SELinux will not allow the service to perform the intended action.

Booleans provide a compromise between a too strict policy, which becomes unusable, and a too lenient policy, which leaves a wide attach surface open.

You can list and query the status of an SELinux boolean using the `getsebool` command, and you can change its status using the `setsebool` command.

For example, the Apache Web Server could just serve static web pages, but it also could serve dynamic pages which access databases, send e-mail, and perform a number of other tasks by means of Apache modules and scripting languages such as PHP. To use those features, you must enable booleans such as `httpd_enable_cgi` and `httpd_can_sendmail`.

== Generic Workflow for Troubleshooting SELinux Issues

Whenever you find something that looks like an issue with SELinux, follow these troubleshooting steps:

0. Ensure that the application was not denied access to files, networks, or devices by other Linux mechanisms such as file system permissions and packet filtering. Remember that SELinux does not override other Linux security mechanisms.

1. Install SELinux support tools from packages such as `setools-console` and `policycoreutils-python-utils`.

2. Ensure that the audit daemon is active.

3. Check that SELinux is enabled and in enforcing mode.

4. Check that the targeted policy was loaded.

5. Review SELinux messages in the audit log using `ausearch`.

6. Put the application's confined domain in permissive mode, and reproduce the scenario which creates the issue.

7. If necessary, put the entire system in permissive mode, and reproduce the scenario.

8. Use SELinux tools, such as `audit2why` and `sealert`, to help you interpret AVC errors and suggest potential fixes.

9. Implement configuration changes, such as relabeling files and enabling booleans.

10. If all else fails, create a custom policy module.

11. If you put a confined domain or a system in permissive mode, restore it to enforcing mode.

At any of the steps above, you may get sufficient information for establishing a root cause and propose a resolution. If the resolution doesn't work, restart from step zero, until you are satisfied you resolved the issue.

== Next Steps

We will perform two activities where you troubleshoot and fix SELinux issues. In between those activities, we will learn how to interpret SELinux errors, especially AVC errors.


== FROM HERE ON, RAW COPY-AND-PASTE FROM OTHER SOURCES, PENDING REORGANIZATION

https://docs.google.com/presentation/d/11K6ykCk2d9QySZ3rVzJWnX6FADEGLCacVAmumbBlENs/edit#

=== selinux-policy-devel policycoreutils-python-utils: slides #136-144

SUPPORT SELINUX CASES

Very busy and confusing diagram of a workflow for troubleshooting SELinux issues. Keep it? Redraw for legibility?

[source,subs="verbatim,quotes"]
--
# dnf install selinux-policy-devel policycoreutils-python-utils
--

Is audit daemon running? 
[source,subs="verbatim,quotes"]
--
# systemctl status auditd.service
--

Is SELinux enabled? 
[source,subs="verbatim,quotes"]
--
# getenforce
--

Put SELinux to permissive 
[source,subs="verbatim,quotes"]
--
# setenforce 0
--
Reproduce the scenario

What does ausearch say?
[source,subs="verbatim,quotes"]
--
# ausearch -m AVC -m USER_AVC -ts today
--

Maybe needed
[source,subs="verbatim,quotes"]
--
# semodule -DB
--

