:time_estimate: 8

= Lab: Configure SELinux for a Web Application

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Troubleshoot SELinux errors from an Apache Web Server running server-side scripting applications and configure SELinux to fix those errors.

== Before you Begin

You need a RHEL machine to which you have either the root password or unrestricted sudo, and also access to Red Hat Enterprise Linux package repositories, to install any missing packages. That machine must also be configured with:

* SELinux enabled and enforced, using the targeted policy.
* The `setools-console` package.
* The `policycoreutils-python-utils` package.
* The `httpd` package.
* The `mysqld-server` package.
* The `git` client.

These instructions were tested on RHEL 9.3 but should work with minimal change on older releases (since RHEL 7) and newer releases.


== Instructions

1. Download a sample website with includes dynamic pages using the PHP server-side scripting language.
+
1.1. Clone the course samples repository, if you didn't in a previous activity, and enter the `quotes` directory.
+
[source,subs="verbatim,quotes"]
--
$ *git clone https://github.com/RedHatQuickCourses/selinux-policies-samples.git*
...
Resolving deltas: 100% (25/25), done.
$ *cd selinux-policies-samples/quotes*
$ *ls*
db.sql  hello.php  index.html  quotes.php
--
+
1.2. Verify if the prerequisite Apache Web Server and MySQL database server packages are installed. It should be fine if you have different versions of those packages. If they are not, please install them:
+
[source,subs="verbatim,quotes"]
--
$ *rpm -q httpd*
httpd-2.4.57-5.el9.x86_64
$ *rpm -q mysql-server*
mysql-server-8.0.32-1.el9_2.x86_64
--
+
1.3. Install the PHP scripting language, its CLI utility, and its MySQL database driver, as prerequisites of the quotes web site:
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf -y install php php-cli php-mysqlnd*
...
Complete!
--
+
1.4. Start the Apache Web Server and the MySQL database server:
+
[source,subs="verbatim,quotes"]
--
$ *systemctl start httpd*
$ *systemctl start mysqld*
$ *systemctl is-active httpd*
active
$ *systemctl is-active mysqld*
active
--
+
1.5. Use the provided SQL script to initialize the quotes database:
+
[source,subs="verbatim,quotes"]
--
$ *sudo mysql < db.sql*
--

2. Install the quote application on the Apache Web Server document root by making a very common mistake: moving files between directories with different SELinux contexts:
+
2.1. Move the welcome page and the dynamic pages from the git repository to the Apache Web Server document root:
+
[source,subs="verbatim,quotes"]
--
$ *sudo mv *.html *.php /var/www/html/*
$ *ls -Za -1 /var/www/html/*
system_u:object_r:httpd_sys_content_t:s0 .
system_u:object_r:httpd_sys_content_t:s0 ..
    unconfined_u:object_r:user_home_t:s0 hello.php
    unconfined_u:object_r:user_home_t:s0 index.html
    unconfined_u:object_r:user_home_t:s0 quotes.php
--
+
2.2. If the output of the previous command shows an SELinux context type other than `user_home_t` on the HTML and PHP files, force them to the INCORRECT type, in order to emulate the common error:
+
[source,subs="verbatim,quotes"]
--
$ *sudo chcon -t user_home_t /var/www/html/\**
--
+
Remember that, if you move files between different file systems, they do not retain their permissions and SELinux context, but inherit them from the destination directory as they would with a copy operation.

3. Verify that the Apache Web Server cannot serve the welcome page you just installed.
+
3.2 Try to retrieve the welcome page. It is expected to fail. Feel free to use a real web browser instead of the `curl` command, if you like:
+
[source,subs="verbatim,quotes"]
--
$ *curl http://127.0.0.1/*
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>
--
+
3.3. Check that the welcome page is world-readable, so the access error was not caused by file permission bits:
+
[source,subs="verbatim,quotes"]
--
$ *ls -la /var/www/html/*
total 12
drwxr-xr-x. 2 root    root     59 Jul 22 18:22 .
drwxr-xr-x. 4 root    root     33 Jul 18 14:48 ..
-rw-r--r--. 1 student student  53 Jul 22 16:58 hello.php
-rw-r--r--. 1 student student 328 Jul 22 17:32 index.html
-rw-r--r--. 1 student student 955 Jul 22 18:22 quotes.php
--
+
3.4. Check that the audit log has an event from SELinux:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m avc -ts recent*
----
time->Mon Jul 22 17:09:56 2024
type=PROCTITLE msg=audit(1721682596.879:196): proctitle=2F7573722F7362696E2F6874747064002D44464F524547524F554E44
type=SYSCALL msg=audit(1721682596.879:196): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=7f023400a4e8 a2=80000 a3=0 items=0 ppid=3099 pid=3108 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="httpd" exe="/usr/sbin/httpd" subj=system_u:system_r:httpd_t:s0 key=(null)
type=AVC msg=audit(1721682596.879:196): avc:  denied  { read } for  pid=3108 comm="httpd" name="index.html" dev="vda4" ino=25927060 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0
--
+
Notice that the event refers to the `httpd` executable and to the `index.html` file, so it must be related to the error retrieving the welcome page.

4. Fix the context on HTML and PHP pages and verify that the quotes dynamic page fails to work.
+
4.1. Restore the default SELinux context of web pages, as stated by the currently loaded policy:
+
[source,subs="verbatim,quotes"]
--
$ *restorecon -fv /var/www/html/\**
Relabeled /var/www/html/hello.php from unconfined_u:object_r:user_home_t:s0 to system_u:object_r:httpd_sys_content_t:s0
Relabeled /var/www/html/index.html from unconfined_u:object_r:user_home_t:s0 to system_u:object_r:httpd_sys_content_t:s0
Relabeled /var/www/html/quotes.php from unconfined_u:object_r:user_home_t:s0 to system_u:object_r:httpd_sys_content_t:s0
--
+
4.2. Revisit the welcome page, it should work this time:
+
[source,subs="verbatim,quotes"]
--
$ *curl http://127.0.0.1/*
<html>
  <body>
    <h1>Famous Quotes</h1>
    <p>
    Click to get a  <a href="quotes.php">random quote</a> related to the IT field.
    <p>
    The selected quotes are based on the blog post by <a href="https://www.freshworks.com/freshservice/general/top-it-quotes-blog/">Ankit Ranjan</a>.
  </body>
</html>
--
+
4.3. Click the link to the "random quote", or visit it using the `curl` command. You should get what looks, from a web browser, like an empty page, but which is actually a truncated response. Ignore for now the issue of having a badly designed application which does not perform any error handling:
+
[source,subs="verbatim,quotes"]
--
$ *curl http://127.0.0.1/quotes.php*
<html>
<body>
<h1>
--
+
4.4. Check the Apache Web Server logs. The error log should show only the error from the first attempt to access the web page, and the access log should show an internal error (HTTP 500) which is quite common with unhandled errors from PHP scripts:
+
[source,subs="verbatim,quotes"]
--
$ *sudo tail -n 1 /var/log/httpd/error_log*
[Mon Jul 22 17:09:56.881213 2024] [core:error] [pid 3108:tid 3297] (13)Permission denied: [client 127.0.0.1:49108] AH00132: file permissions deny server access: /var/www/html/index.html
$ *sudo tail -n 1 /var/log/httpd/access_log*
127.0.0.1 - - [22/Jul/2024:17:33:16 -0400] "GET /quotes.php HTTP/1.1" 500 - "-" "curl/7.76.1"
--
4.5. Check the audit log for SELinux errors, and you should see an event which mentions both PHP and MySQL:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m avc -ts recent*
----
time->Mon Jul 22 17:33:16 2024
type=PROCTITLE msg=audit(1721683996.862:250): proctitle=7068702D66706D3A20706F6F6C20777777
type=SYSCALL msg=audit(1721683996.862:250): arch=c000003e syscall=42 success=no exit=-13 a0=6 a1=7fec3b803040 a2=10 a3=7ffef0c425a0 items=0 ppid=3100 pid=3101 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="php-fpm" exe="/usr/sbin/php-fpm" subj=system_u:system_r:httpd_t:s0 key=(null)
type=AVC msg=audit(1721683996.862:250): avc:  denied  { name_connect } for  pid=3101 comm="php-fpm" dest=3306 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:mysqld_port_t:s0 tclass=tcp_socket permissive=0
--

5. Verify that the Apache Web Server can run PHP scripts. Also verify that PHP scripts, when executed interactively, can access MySQL databases.
+
5.1. Visit the hello page, which is hidden from normal navigation. It is quite common that dynamic websites have a few hidden pages for troubleshooting purposes and for health reporting to monitoring systems:
+
[source,subs="verbatim,quotes"]
--
$ *curl http://127.0.0.1/hello.php*
<html>
<body>
Hello world
</body>
</html>
--
+
5.2. Run the quotes script interactively. You may get a different quote, but it proves the script works:
+
[source,subs="verbatim,quotes"]
--
$ *php -f /var/www/html/quotes.php*
<html>
<body>
<h1>
IT is ever-changing and there is a need to evolve in order to stay relevant.
</h1>
<p>
<a href="/index.html">Back</a> | <a href="../quotes.php">Another quote</a>
</p>
</body>
</html>
--
+
It is expected that applications which fail to run on confined domains from system services work on unconfined domains from interactive users.

6. Enable the boolean that allows the Apache Web Server confined domain to open network connections to databases and retry the dynamic page.
+
6.1. List the available booleans from the Apache Web Server, as you know many optional features are enabled by those booleans. The list is quite long, but among them are many booleans related to network connections:
+
[source,subs="verbatim,quotes"]
--
$ *getseboolean -a | grep httpd*
...
httpd_can_network_connect --> off
httpd_can_network_connect_cobbler --> off
httpd_can_network_connect_db --> off
httpd_can_network_memcache --> off
...
--
+
6.2. Enable the boolean which allows network connections to databases:
+
[source,subs="verbatim,quotes"]
--
$ *sudo setsebool httpd_can_network_connect_db on*
$ *getsebool httpd_can_network_connect_db*
httpd_can_network_connect_db --> on
--
+
6.3. Revisit the "random quote" page. It should now work:
+
[source,subs="verbatim,quotes"]
--
$ *curl http://127.0.0.1/quotes.php*
<html>
<body>
<h1>
The 4 Ps for Change and Release: Planning Prevents Poor Performance.
</h1>
<p>
<a hef="/quotes.php">Another quote</a>
</body>
<p>
<a href="/index.html">Back</a> | <a href="../quotes.php">Another quote</a>
</p>
</body>
</html>
--

== Next Steps

Just setting the correct context labels on resources and enabling the correct booleans can go a long way to ensure you can run applications securely under the targeted policy set by RHEL.

The next section will focus on interpreting SELinux audit events and tools which help you assess if it's the case of configuring a server or adding a custom policy.
