:time_estimate: 5

= Lab: Supporting SElinux

_Estimated reading time: *{time_estimate} minutes*._

// This is my first hands-on with Antora, look for formatting templates

// Different than the previous GE, this one requires setting booleans to fix issues.

// Using NFS requires two VMs, right? Maybe replace with a PHP app which access MySQL for something more interesting and closer to "applications"

// Mention that some errors might be caused by a previous attempt to "fix" by disabling SELinux?

Objective::

Troubleshoot SELinux errors from an Apache Web Server and configure SELinux to fix those errors.

WARNING: Pending Review

== Title

Lorem Ipsum

== FROM HERE ON, RAW COPY-AND-PASTE FROM OTHER SOURCES, PENDING REORGANIZATION

https://docs.google.com/presentation/d/11K6ykCk2d9QySZ3rVzJWnX6FADEGLCacVAmumbBlENs/edit#

=== Http with NFS: slides #145-158

What does ausearch say?
[source,subs="verbatim,quotes"]
--
# ausearch -m AVC -m USER_AVC -ts today
--

type=AVC msg=audit(1395177286.929:1638): avc:  denied  { read } for  pid=6591 comm="httpd" name="webpages" dev="0:37" ino=2112 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:nfs_t:s0 tclass=dir

[source,subs="verbatim,quotes"]
--
# ausearch -m AVC -m USER_AVC -ts today | audit2allow
...
# sealert -a avc
...
--

[source,subs="verbatim,quotes"]
--
#============= httpd_t ==============
#!!!! This avc can be allowed using one of the these booleans:
# 	httpd_use_nfs, git_system_use_nfs
allow httpd_t nfs_t:dir read;
--

[source,subs="verbatim,quotes"]
--
# semanage boolean -l | grep httpd_use_nfs
# semanage boolean -m --on httpd_use_nfs
--

type=AVC msg=audit(1491948261.488:599): avc:  denied  { name_bind } for  pid=5920 comm="httpd" src=3131 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket

[source,subs="verbatim,quotes"]
--
# semanage port -l | grep 80
http_port_t                	tcp  	80, 81, 443, 488, 8008,   8009, 8443, 9000

# sesearch -A -s httpd_t -t http_port_t  -c tcp_socket  -p name_bind
Found 1 semantic av rules:
  allow httpd_t http_port_t : tcp_socket name_bind ;

# semanage port -a -t http_port_t -p tcp 3131
# semanage port -l | grep http_port_t
http_port_t                	tcp  	3131, 80, 81, 443, 488, 8008,   8009, 8443, 9000
--

type=AVC msg=audit(1491949594.146:622): avc:  denied  { read } for  pid=6094 comm="httpd" name="index.html" dev="dm-0" ino=13485999 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:var_t:s0 tclass=file

[source,subs="verbatim,quotes"]
--
# matchpathcon /var/test_www/html/index.html
/var/test_www/html/index.html    system_u:object_r:var_t:s0

# matchpathcon /var/www/html/index.html
/var/www/html/index.html    system_u:object_r:httpd_sys_content_t:s0

# semanage fcontext -a -t httpd_sys_content_t "/var/test_www(/.*)?"
# restorecon -Rv /var/
--

type=AVC msg=audit(1491949594.146:622): avc:  denied  { read } for  pid=6094 comm="httpd" name="index.html" dev="dm-0" ino=13485999 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:unlabeled_t:s0 tclass=file

[source,subs="verbatim,quotes"]
--
# restorecon -Rv /
# fixfiles onboot && reboot
--

// This example of allowing httpd access to mysqld logs seem strage. Something to justify creating a fix-up policy? Could it be from a web UI for mysql?

type=AVC msg=audit(1491949594.146:622): avc:  denied  { read } for  pid=6094 comm="httpd" name="db" dev="dm-0" ino=13485999 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:mysql_log_t:s0 tclass=file

[source,subs="verbatim,quotes"]
--
# audit2allow -i avc
#============= httpd_t ==============
allow httpd_t mysqld_log_t:file read;
--

[source,subs="verbatim,quotes"]
--
# audit2allow -i avc -M local_httpd
******************** IMPORTANT ***********************
To make this policy package active, execute:
semodule -i local_httpd.pp
# semodule -i local_httpd.pp
--


