:time_estimate: 15

= Lab: Troubleshoot SELinux policies

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Run an Apache Web Server with changes to its default configuration under the targeted policy set from RHEL.

== Before you Begin

You need a RHEL machine to which you have either the root password or unrestricted sudo, and also access to Red Hat Enterprise Linux package repositories, to install any missing packages. That machine must also be configured with:

* SELinux enabled and enforcing, using the targeted policy.
* The `setools-console` package.
* The `policycoreutils-python-utils` package.
* The `httpd` package.

These instructions were tested on RHEL 9.3 but should work with minimal change on older releases (since RHEL 7) and newer releases.

== Instructions

1. Change the configuration of your Apache Web Server to listen to a non-standard TCP port and serve web pages from a different document root.
+
1.1. Verify that the Apache Web Server is installed but not running. It is OK if you have a different version of the `httpd` package:
+
[source,subs="verbatim,quotes"]
--
$ *rpm -q httpd*
httpd-2.4.57-5.el9.x86_64
$ *systemctl is-active httpd*
inactive
--
+
1.2. Save a backup copy of the configuration file, just in case:
+
[source,subs="verbatim,quotes"]
--
$ cp /etc/httpd/conf/httpd.conf $HOME/httpd.conf.sav
--
+
1.3. Edit the `/etc/httpd/conf/httpd.conf` file and change the following three lines:
+
[source,subs="verbatim,quotes"]
--
...
Listen 30000
...
DocumentRoot "/var/website"
...
# Further relax access to the default document root:
<Directory "/var/website">
...
--
+
You can find a copy of the configuration file with all changes already applied in the https://github.com/RedHatQuickCourses/selinux-policies-samples/blob/main/website/httpd.conf[sample applications] git repository.
+
1.4. Create a test website:
+
[source,subs="verbatim,quotes"]
--
$ *sudo mkdir /var/website*
$ *sudo echo "<h1>Minimal Web Site</h1>" > /var/website/index.html*
--
1.5. Make the HTML files public, so the web server (and everything else) can access them:
+
[source,subs="verbatim,quotes"]
--
$ *sudo chmod a+rx /var/website/*
$ *sudo chmod a+r /var/website/index.html*
--

2. Start the Apache Web Server, verify that it fails to serve web pages, and search for AVC error messages.
+
2.1. Try to start the Apache Web Server, it is expected to fail:
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl start httpd*
Job for httpd.service failed because the control process exited with error code.
See "systemctl status httpd.service" and "journalctl -xeu httpd.service" for details.
--
2.2. The web server status shows that it could not listen to the configured port. This shouldn't be an issue because the `httpd` process starts as root.
+
[source,subs="verbatim,quotes"]
--
$ *systemctl status httpd.service*
...
Jul 19 14:27:36 servera.lab.example.com systemd[1]: Starting The Apache HTTP Server...
Jul 19 14:27:36 servera.lab.example.com httpd[1582]: (13)Permission denied: AH00072: make_sock: could not bind to address [::]:30000
Jul 19 14:27:36 servera.lab.example.com httpd[1582]: (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:30000
...
--
2.3. Search for recent AVC errors.
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -ts recent*
----
time->Fri Jul 19 14:27:36 2024
type=PROCTITLE msg=audit(1721413656.365:161): proctitle=2F7573722F7362696E2F6874747064002D44464F524547524F554E44
type=SYSCALL msg=audit(1721413656.365:161): arch=c000003e syscall=49 success=no exit=-13 a0=4 a1=557ed0e8c438 a2=1c a3=7ffc8c05e0fc items=0 ppid=1 pid=1582 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="httpd" exe="/usr/sbin/httpd" subj=system_u:system_r:httpd_t:s0 key=(null)
type=AVC msg=audit(1721413656.365:161): avc:  denied  { name_bind } for  pid=1582 comm="httpd" src=30000 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=0
--
+
You might expect a second AVC on the new document root, but the Apache Web Server terminated with an error code before it tried to open any web page. We will get there shortly.
+
In the previous AVC error, notice the following fields, starting from the end of the message and going backward:
+
* The resource class (`t_class`) of `tcp_socket`
* The resource context (`tcontext`) of type `unreserved_port_t`
* The domain context (`scontext`) of type `httpd_t`
* The resource name (`src`) which matches the port number `30000`
* The message (`msg`) which includes the string "denied"
* The audit event type (`type`) of `AVC`
* The executable file (`exec`) of `/usr/sbin/httpd`

3. Get an explanation for the AVC error.
+
3.1. In a real scenario, there could be multiple AVC denials from different processes, and you would triage and save them into different files to process in small groups, or one-by-one. Because we have only one AVC error, we can pipe the output of `ausearch` directly into `audit2why`
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -ts recent | audit2why*
type=AVC msg=audit(1721413656.365:161): avc:  denied  { name_bind } for  pid=1582 comm="httpd" src=30000 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=0

        Was caused by:
        The boolean nis_enabled was set incorrectly. 
        Description:
        Allow nis to be enabled

        Allow access by executing:
        # setsebool -P nis_enabled 1
--
+
Notice that `audit2why` suggests an INCORRECT way of fixing the AVC, so do NOT follow its advice. You know your static website has no need of enabling Network Information Systems (NIS), which is nowadays considered a very outdated technology.
+
3.2. If you took too long to review the AVC error, the previous step might return "<no matches>". In this case, you can filter by the application binary, which is also useful when there are AVC errors from multiple processes:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -x /usr/sbin/httpd | audit2why*
... same output as the previous step ...
--
+
3.3. To illustrate how the suggestion from `audit2why` could look more sane, here's the output you would get if, instead of 30000, you configure your Apache Web Serve to listen on port 8000:
+
[source,subs="verbatim,quotes"]
--
type=AVC msg=audit(1721416004.455:243): avc:  denied  { name_bind } for  pid=5343 comm="httpd" src=8000 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:soundd_port_t:s0 tclass=tcp_socket permissive=0

        Was caused by:
                Missing type enforcement (TE) allow rule.

                You can use audit2allow to generate a loadable module to allow this access.
--
+
In this case, `audit2why` suggests creating a custom policy module to fix the AVC. Sometimes this can be the right approach, but in this particular case the loaded policy already assigns TCP port 8000 to a different resource type (`soundd_port_t`). It would be better to avoid interfering with the default policies from RHEL, but if you have to, you could add allow rules so the Apache Web Server has access to more resource types.
+
Feel free to change your Apache Web Server configuration and retry the previous steps to see this different suggestion by yourself. Or if you prefer, just proceed to the next step.


4. Assess if the suggestion from `audit2why` was a good one.
+
4.1. We already know that our Apache Web Server configuration does not require NIS, and that the previous recommendation looks odd. But let's check what enabling that boolean entails:
+
[source,subs="verbatim,quotes"]
--
$ *sudo sesearch -A -s httpd_t -b nis_enabled*
...
allow nsswitch_domain reserved_port_type:tcp_socket name_connect; [ nis_enabled ]:True
...
allow nsswitch_domain unreserved_port_t:tcp_socket name_connect; [ nis_enabled ]:True
...
--
+
It is a long list of allow rules, which raises a red flag. After all, we want network servers to run under the most restrictive policy we can.
+
4.2. Check the range of ports that would be allowed by the boolean.
It includes resource types which grant a large range of TCP ports:
+
[source,subs="verbatim,quotes"]
--
$ *semanage port -l | grep tcp | grep 'unreserved_port_t'*
unreserved_port_t              tcp      61000-65535, 1024-3276
--
+
That made `audit2why` suggest the boolean. We do not want our web server vulnerable to exploits that would listen to more network ports than it needs. Listening to additional ports is a common behavior of malware that installs back-doors into a system.
+
By the way, the fact that NIS requires such a large range of network ports is among the reasons the technology is considered insecure nowadays. The targeted policy from RHEL includes many booleans to support legacy technologies and those booleans are disabled by default. You should be careful to not enable them unless there's a real need and you provide some mitigation for the increased exposure.

5. Because we didn't like the suggestion from `audit2why`, check if the `sealert` provides a better suggestion.
+
5.1. Save the AVC errors into a text file:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -x /usr/sbin/httpd > avc.log*
--
+
5.2. Install the `sealert` tool, if it's not available on your test machine:
+
[source,subs="verbatim,quotes"]
--
$ *dnf -y install setroubleshoot-server*
...
Complete!
--
+
5.3. Process the text file with `sealert`. It gives a long output, with multiple suggestions. Let's review them one by one:
+
[source,subs="verbatim,quotes"]
--
$ *sealert -a avc.log*
found 1 alerts in avc.log
--------------------------------------------------------------------------------

SELinux is preventing /usr/sbin/httpd from name_bind access on the tcp_socket port 30000.
...
--
+
5.4. The first suggestion is to change the resource type for port 30000. It seems a good one, but the Apache Web Server can listen to multiple port types and we need some guidance on which one, if we decide to follow this suggestion:
+
[source,subs="verbatim"]
--
...
*****  Plugin bind_ports (92.2 confidence) suggests   ************************

If you want to allow /usr/sbin/httpd to bind to network port 30000
Then you need to modify the port type.
Do
# semanage port -a -t PORT_TYPE -p tcp 30000
    where PORT_TYPE is one of the following: http_cache_port_t, http_port_t, jboss_management_port_t, jboss_messaging_port_t, ntop_port_t, puppet_port_t.
...
--
+
5.5. The second suggestion is enabling the same boolean we got from `audit2why`, which we do not consider a good suggestion:
+
[source,subs="verbatim"]
--
...
*****  Plugin catchall_boolean (7.83 confidence) suggests   ******************

If you want to allow nis to enabled
Then you must tell SELinux about this by enabling the 'nis_enabled' boolean.
You can read 'httpd_selinux' man page for more details.
Do
setsebool -P nis_enabled 1
...
--
+
5.6. The third and latest suggestion is creating a custom policy module, and this is something we wish to avoid, if we can:
+
[source,subs="verbatim"]
--
...
*****  Plugin catchall (1.41 confidence) suggests   **************************

If you believe that httpd should be allowed name_bind access on the port 30000 tcp_socket by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'httpd' --raw | audit2allow -M my-httpd
# semodule -X 300 -i my-httpd.pp
...
--
+
We can ignore the remaining of the output of `sealert`, which provides contextual information about the system where it runs and the AVC errors it processes.

6. Review the online policy docs for a proper fix.
+
The first suggestion from `sealert`, of changing the resource type of TCP port 30000, seems to be the best one. It is the more restrictive one, but it lists a number of candidate port types that the Apache Web Server confined domain has access to and we must pick one.
+
You could use the `seinfo`, `sesearch`, and `semanage` commands, which we already explored in previous labs, to introspect the loaded SELinux policy and figure the resource type for listening to HTTP connections. Instead of guessing, let's review the policy documentation for the purpose of each of the port types.
+
6.1. Install the `selinux-policy-docs` package and review the man pages for the Apache Web Server policy module.
+
[source,subs="verbatim,quotes"]
--
$ *dnf -y install selinux-policy docs*
...
Complete!
$ *man httpd_selinux*
...
--
+
Browse the main page and see it includes a somewhat long list of booleans from the policy, which is followed by a list of port types. Skip the list of managed files which just state resource domains the domain has access to, and see the list of file contexts. Most of the time, the information you need is in either the lists of port types or the list of file contexts.
+
6.2. From the man page, the following resource type seems to be the one we need:
+
[source,subs="verbatim,quotes"]
--
...
       http_port_t

       Default Defined Ports:
                 tcp 80,81,443,488,8008,8009,8443,9000
...
--
+
6.4. Check that your system sets only the default ports to the `http_port_t` type:
+
[source,subs="verbatim,quotes"]
--
$ *sudo semanage port -l | grep http_port_t*
http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443, 9000
...
--
+
6.5. Label the 30000 TCP port with the correct SELinux context:
+
[source,subs="verbatim,quotes"]
--
$ *sudo semanage port -a -t http_port_t -p tcp 30000*
--
+
6.6. And verify the new port was added to the policy:
+
[source,subs="verbatim,quotes"]
--
$ *sudo semanage port -l | grep http_port_t*
http_port_t                    tcp      30000, 80, 81, 443, 488, 8008, 8009, 8443, 9000
...
--


7. Try again starting the Apache Web Server and check if there are more AVC errors.
+
7.1. Start Apache Web and verify it successfully listens for connections on the new port:
+
[source,subs="verbatim,quotes"]
--
$ *systemctl start httpd*
$ *systemctl is-active httpd*
active
$ *ss -ltnp | grep 30000*
LISTEN 0      511                *:30000            *:*    users:(("httpd",pid=5682,fd=4),("httpd",pid=5681,fd=4),("httpd",pid=5680,fd=4),("httpd",pid=5678,fd=4))
--
+
7.2. Do not celebrate yet, a running web server may still not be able to serve HTML pages. Try accessing the website on localhost:
+
[source,subs="verbatim,quotes"]
--
$ *curl http://127.0.0.1:30000/index.html*
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
...
--
7.3. You are sure the `httpd` daemon has file access permissions to the `/var/website/index.html` file, right?
+
[source,subs="verbatim,quotes"]
--
ls -l /var/website/index.html 
-rw-r--r--. 1 root root 26 Jul 19 14:22 /var/website/index.html
--
+
7.4. Verify if there are new AVC errors. You should see a "denied" entry which refers to a `path` of `/var/website/index.html`
+
[source,subs="verbatim,quotes"]
--
ausearch -m AVC -ts recent 
----
time->Fri Jul 19 16:26:33 2024
type=PROCTITLE msg=audit(1721420793.896:460): proctitle=2F7573722F7362696E2F6874747064002D44464F524547524F554E44
type=SYSCALL msg=audit(1721420793.896:460): arch=c000003e syscall=262 success=no exit=-13 a0=ffffff9c a1=7f1bc8004af8 a2=7f1bddffa8b0 a3=0 items=0 ppid=5678 pid=5682 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="httpd" exe="/usr/sbin/httpd" subj=system_u:system_r:httpd_t:s0 key=(null)
type=AVC msg=audit(1721420793.896:460): avc:  denied  { getattr } for  pid=5682 comm="httpd" path="/var/website/index.html" dev="vda4" ino=26341349 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:var_t:s0 tclass=file permissive=0
--
+
Because `httpd` runs in a confined domain, it is expected that it has no access to most resource types, such as `var_t` from our web page, which is the default context set by the loaded policy for all files under the `/var` directory.
+
7.5. Check the advice, if any, from `audit2why`:
+
[source,subs="verbatim,quotes"]
--
$ *ausearch -m AVC -ts recent | audit2why*
type=AVC msg=audit(1721420793.896:460): avc:  denied  { getattr } for  pid=5682 comm="httpd" path="/var/website/index.html" dev="vda4" ino=26341349 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:var_t:s0 tclass=file permissive=0

        Was caused by:
                Missing type enforcement (TE) allow rule.

                You can use audit2allow to generate a loadable module to allow this access.
--
+
It suggests generating a policy module, which would allow the `httpd_t` domain type access to the `var_t` resource type. It is a best practice to avoid adding allow rules to the loaded policies, in order to keep a minimal attack surface. Fortunately, there is a better fix for this case.
+
7.6. Check the advice from `sealert`:
+
[source,subs="verbatim,quotes"]
$ *ausearch -m AVC -ts recent > avc2.log*
$ *sealert -a avc2.log*
...
+
The first suggestion looks like a good one:
+
[source,subs="verbatim"]
--
*****  Plugin restorecon (94.8 confidence) suggests   ************************

If you want to fix the label. 
/var/website/index.html default label should be httpd_sys_content_t.
Then you can run restorecon. The access attempt may have been stopped due to insufficient permissions to access a parent directory in which case try to change the following command accordingly.
Do
# /sbin/restorecon -v /var/website/index.html
...
--
+
The other suggestion from `sealert` provides a long list of file types the Apache Web Server domains have access to.


8. Change the context type of the alternate document root.
+
8.1. Review the `httpd_selinux(8)` man page to confirm the proper resource type for web pages. Or copy it from the default document root:
+
[source,subs="verbatim,quotes"]
--
$ *ls -dZ /var/www/html/*
system_u:object_r:httpd_sys_content_t:s0 /var/www/html/
--
+
8.2. Add the `/var/website` directory tree to the resource type for web pages:
+
[source,subs="verbatim,quotes"]
--
$ *semanage fcontext -a -t httpd_sys_content_t "/var/website(/.*)?"*
$ *restorecon -Rv /var/website*
Relabeled /var/website from unconfined_u:object_r:var_t:s0 to unconfined_u:object_r:httpd_sys_content_t:s0
Relabeled /var/website/index.html from unconfined_u:object_r:var_t:s0 to unconfined_u:object_r:httpd_sys_content_t:s0
--

9. Restart the Apache Web Server and check that now you can access the static website.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl restart httpd*
$ *curl http://127.0.0.1:30000/index.html*
<h1>Minimal Web Site</h1>
--

== Next Steps

Interpreting AVC errors requires careful consideration of what the offending application is trying to do and knowledge of the targeted policy set by RHEL.

Before we start activities related to creating a custom SELinux policy, let's discuss how to ensure multiple servers and desktops have consistent SELinux settings.
