:time_estimate: 5

= Lab: Generate a Generic SElinux Policy Module

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Generate a policy module that runs a compiled application as a permissive domain in confined mode.

WARNING: Pending Review

== Before you Begin

You need a RHEL machine to which you have the root password or unrestricted sudo and access to Red Hat Enterprise Linux package repositories, to install any missing packages. That machine must also be configured with:

* SELinux enabled and enforcing, using the targeted policy.
* The `setools-console` package.
* The `policycoreutils-python-utils` package.
* The `git` client.
* The `gcc-c++`, `make`, and `libcurl-devel` packages.

These instructions were tested on RHEL 9.3 but should work with minimal change on older releases (since RHEL 7) and newer releases.


== Instructions

1. Install a third-party application, if you didn't do it already in a xref:ch1-need:s7-confined-lab.adoc[previous activity].
+
1.1. Clone the course samples repository, if you didn't in a previous activity, and enter the `testapp` diretory.
+
[source,subs="verbatim,quotes"]
--
$ *git clone https://github.com/RedHatQuickCourses/selinux-policies-samples.git*
...
Resolving deltas: 100% (25/25), done.
$ *cd selinux-policies-samples/testapp*
$ *ls*
Makefile  testapp.c  testapp.service
--
+
1.2. Compile and install the test application:
+
[source,subs="verbatim,quotes"]
--
$ *make*
g++ -std=c++11 -g -o testapp testapp.c -lcurl
$ *sudo make install*
install -m 0755 testapp /usr/local/sbin
install -m 0644 testapp.service /usr/lib/systemd/system/
--
+
1.3. Return to your home directory and start the test application:
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *sudo systemctl start testapp*
--
+
1.4. Find the PID of the test application service and check it runs unconfined:
+
[source,subs="verbatim,quotes"]
--
$ *systemctl show --property MainPID --value testapp*
37507
$ *ps -Z 37507*
LABEL                               PID TTY      STAT   TIME COMMAND
system_u:system_r:unconfined_service_t:s0 37507 ? S     0:00 /usr/local/sbin/testapp -d
--

2. Generate a generic policy to run the application confined but in permissive mode.

Lorem Ipsum

== Next Steps

Lorem Ipsum


== FROM HERE ON, RAW COPY-AND-PASTE FROM OTHER SOURCES, PENDING REORGANIZATION

TBD

