:time_estimate: 5

= Lab: Create a Generic SELinux Policy Module

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Generate a policy module that runs a compiled application as a permissive domain in confined mode.

WARNING: Pending Review

IMPORTANT: All ativities in this chapter require the results of the previous activities. You are not required to perform all of them at once, but it's certainly easier. If you must pause between activities, ensure you can contine using the same RHEL machine.

== Before you Begin

You need a RHEL machine to which you have the root password or unrestricted sudo and access to Red Hat Enterprise Linux package repositories, to install any missing packages. That machine must also be configured with:

* SELinux enabled and enforcing, using the targeted policy.
* The `setools-console` package.
* The `policycoreutils-python-utils` package.
* The `git` client.
* The `gcc-c++`, `make`, and `libcurl-devel` packages.

These instructions were tested on RHEL 9.3 but should work with minimal change on older releases (since RHEL 7) and newer releases.

== Instructions

1. Install the sample third-party application, if you didn't do it already in a xref:ch1-need:s7-confined-lab.adoc[previous activity].
+
1.1. Clone the course samples repository and enter the `testapp` diretory.
+
[source,subs="verbatim,quotes"]
--
$ *git clone https://github.com/RedHatQuickCourses/selinux-policies-samples.git*
...
Resolving deltas: 100% (25/25), done.
$ *cd selinux-policies-samples/testapp*
$ *ls*
Makefile  testapp.c  testapp.service
--
+
1.2. Compile and install the test application:
+
[source,subs="verbatim,quotes"]
--
$ *make*
g++ -std=c++11 -g -o testapp testapp.c -lcurl
$ *sudo make install*
install -m 0755 testapp /usr/local/sbin
install -m 0644 testapp.service /usr/lib/systemd/system/
--
+
1.3. Return to your home directory and start the test application:
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *sudo systemctl start testapp*
--

2. Ensure the third-party application is unconfined.
+
2.1. Check that the test application service is still active. It will terminate when it's done retrieving the weather from all cities, and in that case you need to restart it.
+
[source,subs="verbatim,quotes"]
--
$ *systemctl is-active testapp*
active
--
+
2.2. Find the PID of the test application service and check its running with the unconfined domain type:
+
[source,subs="verbatim,quotes"]
--
$ *systemctl show --property MainPID --value testapp*
37507
$ *ps -Z 37507*
LABEL                               PID TTY      STAT   TIME COMMAND
system_u:system_r:unconfined_service_t:s0 37507 ? S     0:00 /usr/local/sbin/testapp -d
--

3. Generate a generic policy module that runs the third-party application confined in a domain but in permissive mode.
+
3.1. Install the SELinux policy and RPM package development tools.
+
[source,subs="verbatim,quotes"]
--
$ *dnf install -y selinux-policy-devel rpm-build*
...
Complete!
--
+
3.2. Create a new directory for the policy and generate a starter policy from the test application application executable:
+
[source,subs="verbatim,quotes"]
--
$ *mkdir selinux-testapp*
$ *cd selinux-testapp*
$ *sepolicy generate --init /usr/local/sbin/testapp*
Created the following files:
/home/student/selinux-testapp/testapp.te # Type Enforcement file
/home/student/selinux-testapp/testapp.if # Interface file
/home/student/selinux-testapp/testapp.fc # File Contexts file
/home/student/selinux-testapp/testapp_selinux.spec # Spec file
/home/student/selinux-testapp/testapp.sh # Setup Script
--
+
3.3. Compile and load the starter policy using the generated script:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ./testapp.sh*
Building and Loading Policy
+ make -f /usr/share/selinux/devel/Makefile testapp.pp
Compiling targeted testapp module
Creating targeted testapp.pp policy package
rm tmp/testapp.mod tmp/testapp.mod.fc
+ /usr/sbin/semodule -i testapp.pp
+ sepolicy manpage -p . -d testapp_t
./testapp_selinux.8
+ /sbin/restorecon -F -R -v /usr/local/sbin/testapp
+ /sbin/restorecon -F -R -v /var/run/testapp.pid
...
+ rpmbuild --define '_sourcedir /home/student/selinux-testapp'
...
Wrote: /home/student/selinux-testapp/testapp_selinux-1.0-1.el9.src.rpm
+ exit 0
--
+
Notice that the script already relabels files as required by the policy rules, especially the test application executable and its PID file.
+
3.4. Check that the script generated new files, especially a binary policy module with extension `.pp` and an RPM package:
+
[source,subs="verbatim,quotes"]
--
$ *ls*
noarch  testapp.fc  testapp.if  testapp.pp  testapp.sh  testapp.te  testapp_selinux-1.0-1.el9.src.rpm  testapp_selinux.8  testapp_selinux.spec  tmp
$ *ls noarch*
testapp_selinux-1.0-1.el9.noarch.rpm
--

4. Restart the third-party application and verify it now runs in a permissive domain:
+
4.1. Restart the test application service to ensure its process runs in the new confined domain:
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl restart testapp*
--
+
4.2. Find the PID of the test application service and check its new domain type:
+
[source,subs="verbatim,quotes"]
--
$ *systemctl show --property MainPID --value testapp*
7966
$ *ps -Z 7966*
LABEL                               PID TTY      STAT   TIME COMMAND
system_u:system_r:testapp_t:s0     7966 ?        S      0:00 /usr/local/sbin/testapp -d
--
+
4.3. Confirm that the new domain type is a permissive domain:
+
[source,subs="verbatim,quotes"]
--
$ *sudo semanage permissive -l*

Builtin Permissive Types 

mptcpd_t
testapp_t
rshim_t
...
--

5. Verify that the loaded policy now contains policies from the custom policy module:
+
5.1. Check that there's a domain transition rule from Systemd to the new confined domain type:
+
[source,subs="verbatim,quotes"]
--
$ *sesearch -T -s init_t -t testapp_exec_t*
type_transition init_t testapp_exec_t:process testapp_t;
$ *sesearch --allow -s init_t -t testapp_t -c process -p transition*
allow initrc_domain daemon:process transition;
--
+
5.2. Check that the new domain type inherits many allow rules from its default attributes, such as access to temporary files, and that the policy also includes some custom allow rules for a new resource type and for its PID file:
+
[source,subs="verbatim,quotes"]
--
$ *sesearch --allow -s testapp_t -c file*
...
allow domain tmpfile:file { append getattr ioctl lock read };
allow domain usermodehelper_t:file { getattr ioctl lock open read };
allow domain usr_t:file map;
allow testapp_t testapp_exec_t:file { entrypoint execute getattr ioctl lock map open read };
allow testapp_t testapp_t:file { append getattr ioctl lock open read write };
allow testapp_t testapp_var_run_t:file { append create getattr ioctl link lock open read rename setattr unlink watch watch_reads write };
--
+
5.3. Check that, despite all of these allow rules, the test application still generates many AVC errors. Do not try to interpret those errors right now.
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -x /usr/local/sbin/testapp*
...
--

6. Take your time to review the generated policy source files: `testapp.if`, `testapp.fc`, and `testapp.te`. Do you see anything in them which you didn't expect?

== Next Steps

The next activity starts the process of reviewing AVC errors from the third-party application and adding policy rules to fix these AVC errors, by focusing on access to system files.


== FROM HERE ON, RAW COPY-AND-PASTE FROM OTHER SOURCES, PENDING REORGANIZATION

TBD

