:time_estimate: 5

= Lab: Reference Interfaces From a Custom SELinux Policy Module

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Resolve AVC errors from a custom policy module, caused by accessing system files, by referring to existing interfaces.

WARNING: Pending Review

IMPORTANT: All ativities in this chapter require the results of the previous activities. You are not required to perform all of them at once, but it's certainly easier. If you must pause between activities, ensure you can contine using the same RHEL machine.

== Before you Begin

You need a RHEL machine to which you have the root password or unrestricted sudo and access to Red Hat Enterprise Linux package repositories, to install any missing packages. That machine must also be configured with:

* SELinux enabled and enforcing, using the targeted policy.
* The `setools-console` package.
* The `policycoreutils-python-utils` package.
* The `selinux-policy-devel` package.
* The `rpm-build` package.

These instructions were tested on RHEL 9.3 but should work with minimal change on older releases (since RHEL 7) and newer releases.


== Instructions

1. This activity is a continuation of the xref:s2-generic-lab.adoc[previous activity]. It requires that the third-party application be already installed as a system service and with a custom policy that runs the application in a permissive domain.
+
1.1. Check that the test application service is still active. It will terminate when it's done retrieving the weather from all cities, and in that case you need to restart it.
+
[source,subs="verbatim,quotes"]
--
$ *systemctl is-active testapp*
inactive
$ *sudo systemctl start testapp*
--
+
1.2. Find the PID of the test application service and check its running in a permissive domain:
+
[source,subs="verbatim,quotes"]
--
$ *systemctl show --property MainPID --value testapp*
39521
$ *ps -Z 39521*
LABEL                               PID TTY      STAT   TIME COMMAND
system_u:system_r:testapp_t:s0    39521 ?        S      0:00 /usr/local/sbin/testapp -d
$ *sudo semanage permissive -l | grep testapp_t*
testapp_t
--
+
1.3. If you need, enter the directory with the custom policy module from the previous activity:
+
[source,subs="verbatim,quotes"]
--
$ *cd selinux-testapp*
$ *ls*
noarch  testapp.fc  testapp.if  testapp.pp  testapp.sh  testapp.te  testapp_selinux-1.0-1.el9.src.rpm  testapp_selinux.8  testapp_selinux.spec  tmp
--

2. Review the first AVC error from the third-pary application.
+
2.1. Analyse the first AVC error from the application:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -x /usr/local/sbin/testapp --just-one*
time->Wed Jul 24 19:30:18 2024
type=PROCTITLE msg=audit(1721849418.111:368): proctitle=2F7573722F6C6F63616C2F7362696E2F74657374617070002D64
type=SYSCALL msg=audit(1721849418.111:368): arch=c000003e syscall=257 success=yes exit=4 a0=ffffff9c a1=4033f3 a2=0 a3=0 items=0 ppid=1 pid=7870 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="testapp" exe="/usr/local/sbin/testapp" subj=system_u:system_r:testapp_t:s0 key=(null)
type=AVC msg=audit(1721849418.111:368): avc:  denied  { open } for  pid=7870 comm="testapp" path="/proc/meminfo" dev="proc" ino=4026532024 scontext=system_u:system_r:testapp_t:s0 tcontext=system_u:object_r:proc_t:s0 tclass=file permissive=1
type=AVC msg=audit(1721849418.111:368): avc:  denied  { read } for  pid=7870 comm="testapp" name="meminfo" dev="proc" ino=4026532024 scontext=system_u:system_r:testapp_t:s0 tcontext=system_u:object_r:proc_t:s0 tclass=file permissive=1
--
+
The AVC is related to reading form the `/proc/meminfo` virtual file. This might be suspicious for the test application, which does nothing that requires system information, but would be common for daemons which auto-tune to allocate more or less memory depending on the total availabe in the system. Anyway, it is harmless from a security perspective.
+
2.2. Get a suggestion to fix the AVC using an interface:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -x /usr/local/sbin/testapp --just-one | audit2allow -R*

require {
        type testapp_t;
}

#============= testapp_t ==============
kernel_read_proc_files(testapp_t)
--
+
Your autogenerated policy module already contains all require statements from `audit2allow`, you only need the reference to the interface at the end of the output.
+
2.3. Find the source file which defines that interface and its comments: 
+
[source,subs="verbatim,quotes"]
--
$ *find /usr/share/selinux/devel/include -name "*.if" -exec grep -l kernel_read_proc_files {} \;*
/usr/share/selinux/devel/include/kernel/kernel.if
--
+
2.4. Open the file from the previous `find` command and search for the interface suggested by the `audit2allow` command:
+
[source,subs="verbatim"]
--
...
########################################
## <summary>
##      Read generic files in /proc.
## </summary>
## <param name="domain">
##      <summary>
##      Domain allowed access.
##      </summary>
## </param>
#
interface(`kernel_read_proc_files',`
...
--
+
This one looks like it allows more than we need. The `/proc` file system might enable access to sensitive information from other processes. Maybe there's another interface, on the same file, which allow access only to harmless informative files such as `/proc/meminfo`?
+
2.5. Scroll down the file until you find this other interface, which seems to be exactly what we need:
+
[source,subs="verbatim"]
--
...
########################################
## <summary>
##      Allows caller to read system state information in /proc.
## </summary>
## <desc>
##      <p>
##      Allow the specified domain to read general system
##      state information from the proc filesystem (/proc).
##      </p>
##      <p>
##      Generally it should be safe to allow this access.  Some
##      example files that can be read based on this interface:
##      </p>
##      <ul>
##              <li>/proc/cpuinfo</li>
##              <li>/proc/meminfo</li>
##              <li>/proc/uptime</li>
##      </ul>
##      <p>
##      This does not allow access to sysctl entries (/proc/sys/*)
##      nor process state information (/proc/pid).
##      </p>
## </desc>
## <param name="domain">
##      <summary>
##      Domain allowed access.
##      </summary>
## </param>
## <infoflow type="read" weight="10"/>
## <rolecap/>
#
interface(`kernel_read_system_state',`
...
--
+
2.6. Find what the `kernel_read_system_state` interface would allow. Because the interface references an attribute, you must generate the output in CIL format, and then perform a search for referentes to the attribute.
+
[source,subs="verbatim,quotes"]
--
$ *macro-expander "kernel_read_system_state(testapp_t)"*
$ *macro-expander -c "kernel_read_system_state(testapp_t)"*
(typeattributeset kernel_system_state_reader (testapp_t ))
$ *sesearch --allow -ds -s kernel_system_state_reader*
allow kernel_system_state_reader proc_t:dir { ioctl lock read };
allow kernel_system_state_reader proc_t:file { getattr ioctl lock open read };
--
+
The output shows it allows only reading files and directories of type `proc_t`.
If you check which files under the `/proc` directory have the `proc_t` type, you will see they provide non-sensitie information about the system.
+
2.7. Get an alternative suggestion to fix the AVC using allow statements:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -x /usr/local/sbin/testapp --just-one | audit2allow -N*


#============= testapp_t ==============
allow testapp_t proc_t:file { open read };
--
+
This is a subset of the rules from the interface. You know that, to read a file, a process has to read its parent directory, so the missing rules probably come from other AVCs that the test application also produces and we didn't review yet. Using the interface would solve those other AVCs too.

3. Update and reload the custom policy.
+
3.1. Add a referente do the interface to the end of the `testapp.te` file:
+
[source,subs="verbatim"]
--
...
logging_send_syslog_msg(testapp_t)

miscfiles_read_localization(testapp_t)

# Before this line, all rules were auto-generated

kernel_read_system_state(testapp_t)
--
+
3.2. Recompile and reload the policy
+
[source,subs="verbatim,quotes"]
--
sudo ./testapp.sh 
...
+ exit 0
--
+
3.3. Restart the test application service, this time recording a timestamp so you can distinguish AVCs from before and after restarting.
+
[source,subs="verbatim,quotes"]
--
$ *TIME=$(date +%T) ; sudo systemctl restart testapp*
--
3.3. Check that there are no more AVCs related to the `/proc` directory:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -x /usr/local/sbin/testapp --start $TIME | grep -c /proc*
0
--

4. Review the next AVC error from the third-party application.
+
4.1. You should see an AVC related to reading files which provide the system-wide trusted CA certificates:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ausearch -m AVC -x /usr/local/sbin/testapp --start $TIME --just-one*
time->Thu Jul 25 19:24:11 2024
type=PROCTITLE msg=audit(1721935451.740:344): proctitle=2F7573722F6C6F63616C2F7362696E2F74657374617070002D64
type=PATH msg=audit(1721935451.740:344): item=0 name="/etc/pki/tls/openssl.cnf" inode=13396 dev=fc:04 mode=0100644 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:cert_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1721935451.740:344): cwd="/"
type=SYSCALL msg=audit(1721935451.740:344): arch=c000003e syscall=257 success=yes exit=3 a0=ffffff9c a1=2280750 a2=0 a3=0 items=1 ppid=5271 pid=5272 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="testapp" exe="/usr/local/sbin/testapp" subj=system_u:system_r:testapp_t:s0 key=(null)
type=AVC msg=audit(1721935451.740:344): avc:  denied  { open } for  pid=5272 comm="testapp" path="/etc/pki/tls/openssl.cnf" dev="vda4" ino=13396 scontext=system_u:system_r:testapp_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=file permissive=1
type=AVC msg=audit(1721935451.740:344): avc:  denied  { read } for  pid=5272 comm="testapp" name="openssl.cnf" dev="vda4" ino=13396 scontext=system_u:system_r:testapp_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=file permissive=1
type=AVC msg=audit(1721935451.740:344): avc:  denied  { search } for  pid=5272 comm="testapp" name="pki" dev="vda4" ino=16922485 scontext=system_u:system_r:testapp_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=dir permissive=1
--
+
Because the test application uses HTTPS to access the weather forecast service, it needs the CA certificates from the internet Public Key Infrastructure (PKI).
+
4.2. Find an interface that match the AVC error:
+
[source,subs="verbatim,quotes"]
--
$ sudo ausearch -m AVC -x /usr/local/sbin/testapp --start $TIME --just-one | audit2allow -R
...
#============= testapp_t ==============
miscfiles_read_certs(testapp_t)
miscfiles_search_generic_cert_dirs(testapp_t)
--
+
We advise you to review the interface file for all interfaces you select, and assess if they are fine or not for your specific needs. In the interest of time, this and the remaining ativities will not perform such tasks, but just use the suggestions from the `audit2allow` command.
+
4.3. Add references to the two interfaces to the end of the `testapp.te` file:
+
[source,subs="verbatim"]
--
...
logging_send_syslog_msg(testapp_t)

miscfiles_read_localization(testapp_t)

# Before this line, all rules were auto-generated

kernel_read_system_state(testapp_t)

miscfiles_read_certs(testapp_t)
miscfiles_search_generic_cert_dirs(testapp_t)
--

5. Verify that the last change fixed AVCs related to TLS certificates.
+
5.1. Rebuild and reload the custom policy. You should get a warning that you are using a deprecated interface.
+
[source,subs="verbatim,quotes"]
--
*sudo ./testapp.sh*
Building and Loading Policy
+ make -f /usr/share/selinux/devel/Makefile testapp.pp
Compiling targeted testapp module
testapp.te:40: Warning: miscfiles_read_certs() has been deprecated, please use miscfiles_read_generic_certs() instead.
Creating targeted testapp.pp policy package
...
+ exit 0
--
+
5.2. Change your policy to not use the deprecated interface anymore:
+
[source,subs="verbatim"]
--
...
logging_send_syslog_msg(testapp_t)

miscfiles_read_localization(testapp_t)

# Before this line, all rules were auto-generated

kernel_read_system_state(testapp_t)

miscfiles_read_generic_certs(testapp_t)
miscfiles_search_generic_cert_dirs(testapp_t)
--
+
5.3. Rebuild and reload the custom policy module, again. Ensure that, this time, you get no warnings.
+
[source,subs="verbatim,quotes"]
--
$ *sudo ./testapp.sh*
Building and Loading Policy
+ make -f /usr/share/selinux/devel/Makefile testapp.pp
Compiling targeted testapp module
Creating targeted testapp.pp policy package
...
+ exit 0
--
+
5.4. Reload the test application service, recording a timestamp, and check if there are any remaining AVC error related to PKI:
+
[source,subs="verbatim,quotes"]
--
$ TIME=$(date +%T) ; sudo systemctl restart testapp
$ sudo ausearch -m AVC -x /usr/local/sbin/testapp --start $TIME | grep -c pki
0
--


== Next Steps

The custom policy is not complete yet. The next activity starts the process of reviewing AVC errors from the third-party application and adding policy rules to fix these AVC errors, by focusing on network access.


[ DESCRIBE THE NEXT AVC? ]

== FROM HERE ON, RAW COPY-AND-PASTE FROM OTHER SOURCES, PENDING REORGANIZATION

Testapp scenario (slides #159-170)
Generate a starter custom policy (slides #171-176)
Domain transition to custom type (slides #177-179)
From AVCs to policy rules (slides #180-197)

https://redhatgov.io/workshops/selinux_policy/exercise2.2/

https://play.instruqt.com/rhel/invite/adj7n5qdsl2y
https://github.com/rhel-labs/instruqt/tree/master/selinux-policy

I got a /proc AVC, like the NPS workshop
slides #183 and instruqt 05-selinux-policy2 got a pid file AVC but afterards they get a proc AVC -- two AVCs on same activity

Why I don't get the pid file AVC?

AVCs from slides:
- pid file #183 -- multiple edits and custom type? #184
- /proc #186 -- interface
- connect to http port #189 -- interface
- resolv.conf #191 -- interface
All rules use interfaces!

slides save all AVCs to a file and interprets them from the file instead of audt2allow
ausearch -m AVC -ts recent > ~/avc_file

AVCs from NPS workshop: (+ not in slides)
- /proc exercise2.2 -- interface
- connect to http port exercise2.3 -- interface (nice checking potential alternatives)
+ sockets exercise2.3 -- audit2allow (just for a variation compared to interfaces? no)
- resolv.conf exercise2.4 -- interface
+ SSL certs exercise2.4 -- interface

AVCs from instruqt (+ not in slides)
- pid file 05-selinux-policy2 -- interface + allow from audit2allow and generic var type 
- /proc 05-selinux-policy2 -- manual manually
+ SSL certs 06-selinux-policy3 - manual interface, warning about mismatch with audit2allow
- connect to http port 06-selinux-policy3 -- interface form audit2allow
+ sockets 06-selinux-policy3 -- allow from audit2allow
- resolv.conf 07-selinux-policy4 -- interface from audit2allow


Install selinux-policy-devel to get policy interface files (and all sources?)

cd /usr/share/selinux/devel/include
find . -type f -name "*.if" -exec grep -H '/proc' {} \; | grep "system state information"
./kernel/kernel.if:##	Allows caller to read system state information in /proc.

manually add to testapp.te
kernel_read_system_state(testapp_t)

keep entries (or just interfaces?) in alphabetical order

restart the service and chek if the AVC relatd to meminfo still exists

sudo ausearch -m AVC -ts recent | grep meminfo | wc -l

maybe use a timestamp to limit ausearch? "recent" is too imprecise. like the instruqt
# All AVCs from the last run
TIME=`date +%T`;export TIME; sudo systemctl restart testapp; sudo ausearch --message AVC --start $TIME

remove /var/run/testapp.pid on restart to get correct label

