:time_estimate: 5

= SELinux Policies, Labels, and Contexts

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Review the fundamental concepts required to read and interpret SELinux policies.

WARNING: Work In Progress

//TODO refactor this and the previous section

== SElinux Labels and Contexts

SELinux works by assigning labels to processes and to objects. Those labels define the SELinux context of a process (or domain) and of an object.

SELinux policy rules allow process with a given label to access objects with a matching label. Process labels may grant different access levels to multiple object labels, for example read-only with some labels and read-write with others.

SELinux policies control not only which process labels gets access to which resource labels, but also which labels processes and resources can get. These are called context transition rules. A context transition rules specifies the new label for a child process after a fork and exec, and the context on files created by process with a given context.

You can configure your RHEL system in such a way that a system administrator can peform day-to-day tasks such as installing packages and creating users but cannot change SELinux policies. Another possibility is allowing system administrators to change labels on resources but not on processes.

[ LABELS AND CONTEXTS NEED WORK ]

== FROM HERE ON, RAW COPY-AND-PASTE FROM OTHER SOURCES, PENDING REORGANIZATION

https://docs.google.com/presentation/d/11K6ykCk2d9QySZ3rVzJWnX6FADEGLCacVAmumbBlENs/edit#


=== SELinux policies and labels: slides #19-52

SELINUX SECURITY POLICY

CORE COMPONENT OF SELINUX
COLLECTION OF SELINUX POLICY RULES
LOADED INTO THE KERNEL BY SELINUX USERSPACE TOOLS

Figure of policy --> tooling --> kernel

ENFORCED BY THE KERNEL
USED TO AUTHORIZE ACCESS REQUESTS ON THE SYSTEM

BY DEFAULT EVERYTHING IS DENIED AND YOU DEFINE POLICY RULES TO ALLOW CERTAIN REQUESTS

SELINUX POLICY RULES

DESCRIBE AN INTERACTION BETWEEN PROCESSES AND SYSTEM RESOURCES

SELINUX POLICY RULE IN HUMAN LANGUAGE

"APACHE process can READ its LOGGING FILE"

SELINUX VIEW OF THAT INTERACTION

ALLOW apache_process apache_log:FILE READ;

apache_process apache_log ARE LABELS

LABELS

ASSIGNED TO PROCESSES
ASSIGNED TO SYSTEM RESOURCES
BY SELINUX SECURITY POLICY
MAP REAL SYSTEM ENTITIES INTO THE SELINUX WORLD

LABELS IN REALITY

STORED IN EXTENDED ATTRIBUTES OF FILE SYSTEMS - EXT2,EXT3, EXT4 ...

[source,subs="verbatim,quotes"]
--
# getfattr -n security.selinux /etc/passwd
getfattr: Removing leading '/' from absolute path names
# file: etc/passwd
security.selinux="system_u:object_r:passwd_file_t:s0"

# ls -Z /etc/passwd
system_u:object_r:passwd_file_t:s0 /etc/passwd
--

SELINUX LABELS CONSIST OF FOUR PARTS

<user>:<role>:<type>:<MLS/MCS>

<user>
Not the same as Linux users
Several Linux users can be mapped to a single SELinux user
object_u is a placeholder for Linux system resources
system_u is a placeholder for Linux processes
Can be limited to a set of SELinux roles

<role>
SELinux users can have multiple roles but only one can be active
object_r is a placeholder for Linux system resources
system_r is a placeholder for system processes
Can be limited to a set of SELinux types

<type>
Security model known as TYPE ENFORCEMENT
In 99% you care only about TYPES
policy rules and interactions between types

<MLS/MCS>
Multi Level Security
Only the MCS part is used in Targeted Policy with the default s0 level
Allow users to mark resources with compartment tags (MCS1, MCS2)
Used for RHEL virtualization and for container security
s0:c1 can not access s0:c2

Figure of users, roles, and screenshots of user contexts

[source,subs="verbatim,quotes"]
--
# useradd -Z staff_u -G wheel staff
# passwd staff
# ssh staff@localhost
$ id -Z
--

=== Skip: targeted policies and types

=== Skip: Type transitions for domains/processes and resources

=== SELinux modes: slides #67-72

SELINUX MODES

ENFORCING
SELINUX SECURITY POLICY IS ENFORCED BY KERNEL

PERMISSIVE
SELINUX SECURITY POLICY IS NOT ENFORCED BY KERNEL
ACCESSES ARE LOGGED

