:time_estimate: 9

= Lab: Explore Labels and Policy Rules in a RHEL Machine

_Estimated reading time: *{time_estimate} minutes*._

// This feels like should follow s1, it does not shows labels and contexts :-(

Objective::

Explore the Labels and SELinux rules included with a default installation of Red Hat Enterprise Linux.

WARNING: Pending Review

== Before you Begin

You need a RHEL machine to which you have either the root password or unrestricted sudo, and also access to Red Hat Enterprise Linux package repositories, to install any missing packages.

Ensure that your system has SELinux enabled and in enforcing mode. Review the xref:s2-setup-lab.adoc[first activity] in this course if you need help with those checks.

These instructions were tested on RHEL 9.3 but should work with minimal change on older releases (since RHEL 7) and newer releases.

== Instructions

1. Log in as a regular Linux user (not root) and verify the SELinux context of your files and processes.
+
1.1. Notice that your home directory and your files have different resource types:
+
[source,subs="verbatim,quotes"]
--
$ *ls -dZ $HOME*
unconfined_u:object_r:user_home_dir_t:s0 /home/student
$ *echo '123' > test.file*
$ *ls -Z test.file*
unconfined_u:object_r:user_home_t:s0 test.file
--
+
1.2. All your process inherit the resource type of your login shell:
+
[source,subs="verbatim,quotes"]
--
$ *ps Z*
LABEL                               PID TTY      STAT   TIME COMMAND
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 1175 pts/0 Ss   0:00 -bash
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 1592 pts/0 R+   0:00 ps Z
--
+
For now, ignore all fields of the domain (process) and resource (files) contexts, except for their types, which are `unconfined_t` and `user_home_dir_t` or `user_home_t`, respectively.

2. Show that SELinux allows the domain to access home directories.
+
2.1. Install the the `setools-console` package, if it's not already installed on your test machine:
+
[source,subs="verbatim,quotes"]
--
$ *sudo install -y setools-console*
...
Complete!
--
+

+
2.2. Search for allow rules using the domain and resource types from the previous step:
+
[source,subs="verbatim,quotes"]
--
$ *sesearch --allow -s unconfined_t -t user_home_dir_t -c file*
allow domain file_type:file map; [ domain_can_mmap_files ]:True
allow files_unconfined_type file_type:file execmod; [ selinuxuser_execmod ]:True
allow files_unconfined_type file_type:file { append audit_access create execute execute_no_trans getattr ioctl link lock map mounton open quotaon read relabelfrom relabelto rename setattr swapon unlink watch watch_mount watch_reads watch_sb watch_with_perm write };
--
+
If you wish, you can also try a similar search for user's home files. Just replace `user_home_dir_t` with `user_home_t` in the previous command.
+
The last entry shows an allow rule which grants permission to apend, create, execute, write, read, and other operations on user's home directories.
+
2.3. If you're adventurous, retry the previous command without one of the `-s`, `-t`, or `-c` options. Be warned that it'll display a large number of allow rules.

3. Run the `passwd` command and check its context and of the system password files.
+
3.1. Run the `passwd` command in the backgrond so it get stuck and you can check its SELinux context:
+
[source,subs="verbatim,quotes"]
--
$ *passwd > /dev/null &*
[1] 1628
$ 

[1]+  Stopped                 passwd > /dev/null
$ *ps -Z 1628*
LABEL                               PID TTY      STAT   TIME COMMAND
unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 1628 pts/0 T   0:00 passwd
--
+
Notice that the `passwd` transitioned from the `unconfined_t` type of its Bash shell to the `passwd_t` type.
+
3.2. Check the context of the password files. The option after `-Z` uses the numeral one for "one file per line":
+
[source,subs="verbatim,quotes"]
--
$ *ls -Z -1 /etc/passwd /etc/shadow*
system_u:object_r:passwd_file_t:s0 /etc/passwd
     system_u:object_r:shadow_t:s0 /etc/shadow
--
+
Notice that there are different SELinux types for `/etc/passwd`, which everyone's supposed to read, and for `/etc/shadow`, which no one is supposed to read.
+
3.3. Don't forget to kill the `passwd` process that you left in the background:
+
[source,subs="verbatim,quotes"]
--
$ *kill %1*
[student@servera ~]$ 
[1]+  Terminated              passwd > /dev/null 
--

4. Check if the `passwd` command and your interactive processes are allowed to access the password files by the SELinux policy.
+
4.1. Notice that the `passwd_t` domain is allowed access to both password files, as expected:
+
[source,subs="verbatim,quotes"]
--
$ *sesearch --allow -s passwd_t -t passwd_file_t -c file*
...
allow passwd_t passwd_file_t:file { append create link rename setattr unlink watch watch_reads write };
$ *sesearch --allow -s passwd_t -t shadow_t -c file*
...
allow passwd_t shadow_t:file { append create getattr ioctl link lock map open read relabelfrom relabelto rename setattr unlink watch watch_reads write };
--
+
4.2. Check that, surprisingly, the `unconfined_t` domain is also allowed access to both password files:
+
[source,subs="verbatim,quotes"]
--
$ *sesearch --allow -s unconfined_t -t passwd_file_t -c file*
...
allow files_unconfined_type file_type:file { append audit_access create execute execute_no_trans getattr ioctl link lock map mounton open quotaon read relabelfrom relabelto rename setattr swapon unlink watch watch_mount watch_reads watch_sb watch_with_perm write };
...
$ *sesearch --allow -s unconfined_t -t shadow_t -c file*
...
allow files_unconfined_type file_type:file { append audit_access create execute execute_no_trans getattr ioctl link lock map mounton open quotaon read relabelfrom relabelto rename setattr swapon unlink watch watch_mount watch_reads watch_sb watch_with_perm write };
--
+
This will make sense in the next section, when we explain the reasoning behind the default policies included with RHEL. For now, let's move forward.
+
4.3. It seems, from the previous output, that unconfined_t domain type inherits from the `files_unconfined_type` attribute. Check that assumption:
+
[source,subs="verbatim,quotes"]
--
$ *seinfo -a files_unconfined_type -x | grep unconfined_t*
   attribute files_unconfined_type;
        certmonger_unconfined_t
        pegasus_openlmi_unconfined_t
        unconfined_t
        virt_qemu_ga_unconfined_t
        vmtools_unconfined_t
        watchdog_unconfined_t
        xdm_unconfined_t
--
+
4.4. Similarly, it seems that the `passwd_file_t` and `shadow_t` resource types inherit from the `file_type` attribute:
+
[source,subs="verbatim,quotes"]
--
$ *seinfo -a file_type -x | grep shadow_t*
        shadow_t
$ *seinfo -a file_type -x | grep passwd_file_t*
        passwd_file_t
--

5. Check that the loaded policy sets default contexts for files under user's home directories and also for password files. You have to use the `semanage` command instead of the `sesearch` command:
+
5.1. First check user home directories, with type `user_home_dir_t`, and user's files, with type `user_home_t`:
+
[source,subs="verbatim,quotes"]
--
$ *sudo semanage fcontext -l | grep user_home_dir_t*
/home/[^/]+                                        directory          unconfined_u:object_r:user_home_dir_t:s0 
/home/[^/]+                                        symbolic link      unconfined_u:object_r:user_home_dir_t:s0 
$ *sudo semanage fcontext -l | grep user_home_t*
/home/[^/]+/.+                                     all files          unconfined_u:object_r:user_home_t:s0 
--
+
5.2. Check the default context for user's SSH keys, to prove that not all files under the `/home` directory get the same context:
+
[source,subs="verbatim,quotes"]
--
$ *sudo semanage fcontext -l | grep ssh_home_t*
/home/[^/]+/\.ansible/cp/.*                        socket             unconfined_u:object_r:ssh_home_t:s0 
/home/[^/]+/\.shosts                               all files          unconfined_u:object_r:ssh_home_t:s0 
/home/[^/]+/\.ssh(/.*)?                            all files          unconfined_u:object_r:ssh_home_t:s0 
--
+
5.3. Check the default context for password files:
+
[source,subs="verbatim,quotes"]
--
$ *sudo semanage fcontext -l | grep shadow_t*
/etc/gshadow.*                                     regular file       system_u:object_r:shadow_t:s0 
/etc/nshadow.*                                     regular file       system_u:object_r:shadow_t:s0 
/etc/security/opasswd                              regular file       system_u:object_r:shadow_t:s0 
/etc/security/opasswd\.old                         regular file       system_u:object_r:shadow_t:s0 
/etc/shadow.*                                      regular file       system_u:object_r:shadow_t:s0 
/etc/tcb/.+/shadow.*                               regular file       system_u:object_r:shadow_t:s0 
/var/db/shadow.*                                   regular file       system_u:object_r:shadow_t:s0
$ *sudo semanage fcontext -l | grep passwd_file_t*
/etc/\.pwd\.lock                                   regular file       system_u:object_r:passwd_file_t:s0 
/etc/group[-\+]?                                   regular file       system_u:object_r:passwd_file_t:s0 
/etc/group\.lock                                   regular file       system_u:object_r:passwd_file_t:s0 
/etc/passwd[-\+]?                                  regular file       system_u:object_r:passwd_file_t:s0 
/etc/passwd\.OLD                                   regular file       system_u:object_r:passwd_file_t:s0 
/etc/passwd\.adjunct.*                             regular file       system_u:object_r:passwd_file_t:s0 
/etc/passwd\.lock                                  regular file       system_u:object_r:passwd_file_t:s0 
/etc/ptmptmp                                       regular file       system_u:object_r:passwd_file_t:s0
--

6. Verify that system services run each under a different context, so they belong to different domains than each other and also different than interactive user logins. Then verify which system services have access to user's files.
+
6.1. Find the context of common system services such as the Secure Shell and Cron daemons.
+
[source,subs="verbatim,quotes"]
--
$ *ps ax -Z | grep sshd*
system_u:system_r:sshd_t:s0-s0:c0.c1023 1117 ?   Ss     0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
system_u:system_r:sshd_t:s0-s0:c0.c1023 1161 ?   Ss     0:00 sshd: student [priv]
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 1174 ? S   0:00 sshd: student@pts/0
system_u:system_r:sshd_t:s0-s0:c0.c1023 1279 ?   Ss     0:00 sshd: student [priv]
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 1282 ? S   0:00 sshd: student@pts/1
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 1711 pts/0 S+   0:00 grep --color=auto sshd
$ *ps ax -Z | grep crond*
system_u:system_r:crond_t:s0-s0:c0.c1023 1119 ?  Ss     0:00 /usr/sbin/atd -f
system_u:system_r:crond_t:s0-s0:c0.c1023 1120 ?  Ss     0:00 /usr/sbin/crond -n
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 1713 pts/0 S+   0:00 grep --color=auto crond
--
+
6.2. Check if the domain types for the Secure Shell and Cron daemons have access to user's home directories.
+
[source,subs="verbatim,quotes"]
--
$ *sesearch --allow -s sshd_t -t user_home_dir_t -c file*
allow domain file_type:file map; [ domain_can_mmap_files ]:True
$ *sesearch --allow -s crond_t -t user_home_dir_t -c file*
allow domain file_type:file map; [ domain_can_mmap_files ]:True
allow files_unconfined_type file_type:file execmod; [ selinuxuser_execmod ]:True
allow files_unconfined_type file_type:file { append audit_access create execute execute_no_trans getattr ioctl link lock map mounton open quotaon read relabelfrom relabelto rename setattr swapon unlink watch watch_mount watch_reads watch_sb watch_with_perm write };
--
+
Notice that the Secure Shell daemon has no access to user's files but the Cron daemon does have access.
+
The Secure Shell daemon starts with elevated privileges, as the root user, and should be constrained as a potential avenue for security exploits.
+
On the other side, regular users are expected to create their own Cron and At jobs, which would be expected to access user's files.
+
6.3. But how does the Secure Shell daemon gets the user's list of authorized keys? We already know there's a different resource type for those files:
+
[source,subs="verbatim,quotes"]
--
$ *ls -Z .ssh/authorized_keys*
unconfined_u:object_r:ssh_home_t:s0 .ssh/authorized_keys
$ *sesearch --allow -s sshd_t -t ssh_home_t -c file*
allow domain file_type:file map; [ domain_can_mmap_files ]:True
allow login_pgm ssh_home_t:file { getattr ioctl lock open read };
allow ssh_server ssh_home_t:file { append create link rename setattr unlink watch watch_reads write };
allow sshd_t user_home_type:file { getattr ioctl lock open read };
--

7. Verify domain transition rules which allow interactive processes and system services to be assigned to their intended domain types.
+
7.1. Check the domain transition rule for interactive processes:
+
[source,subs="verbatim,quotes"]
--
$ *sesearch --allow -s init_t -t unconfined_t -c process -p transition*
allow init_t login_userdomain:process transition;
--
+
7.2. Check that interactice processes can transition to the domain type of the `passwd` command:
+
[source,subs="verbatim,quotes"]
--
$ *sesearch --allow -s unconfined_t -t passwd_t -c process -p transition*
allow unconfined_t domain:process transition;
--
7.3. Check the domain transitions rule for system services:
+
[source,subs="verbatim,quotes"]
--
$ *sesearch --allow -s init_t -t crond_t -c process -p transition*
allow initrc_domain daemon:process transition;
$ *sesearch --allow -s init_t -t sshd_t -c process -p transition*
allow initrc_domain daemon:process transition;
--
+
Domain transitions require a few more rules to exist, such as access to the correct executable file. We will see those rules later, when we learn to create custom policies.

== Next Steps

Before learning to configure SELinux policies and create custom SELinux policies, we must learn the assumptions behind the policy sets included with RHEL, which we see in the next section.

