:time_estimate: 5

= How Red Hat Protects System Services With SELinux on RHEL

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Understand how Red Hat uses SELinux policies within its products.

WARNING: Work In Progress

//TODO refactor this and the previous section

== Title

Lorem ipsum

== FROM HERE ON, RAW COPY-AND-PASTE FROM OTHER SOURCES, PENDING REORGANIZATION

https://docs.google.com/presentation/d/11K6ykCk2d9QySZ3rVzJWnX6FADEGLCacVAmumbBlENs/edit#

=== Targeted policies and types: slides #53-57

IN RHEL9 WE SHIP THE TARGETED SELINUX POLICY BY DEFAULT

WE MOSTLY CARE ONLY ABOUT TYPES

SELINUX ALLOW RULE SYNTAX WITH TYPES

ALLOW TYPE1 TYPE2:OBJECT_CLASS PERMISSION;

ALLOW HTTPD_T HTTPD_LOG_T:FILE READ;

=== Type transitions for domains/processes and resources (slides #58-66)

DOMAIN TRANSITION RULES

TYPE_TRANSITION TYPE1 TYPE2:PROCESS NEW_DOMAIN;

TYPE_TRANSITION INIT_T HTTPD_EXEC_T:PROCESS HTTPD_T;

FILE TRANSITION RULES

TYPE_TRANSITION TYPE1 TYPE2:OBJECT_CLASS NEW_TYPE;

TYPE_TRANSITION HTTPD_T VAR_LOG_T:FILE HTTPD_LOG_T;

FILE NAME TRANSITION RULES

TYPE_TRANSITION TYPE1 TYPE2:OBJECT_CLASS NEW_TYPE “OBJECT_NAME”;

TYPE_TRANSITION HTTPD_T VAR_LOG_T:FILE HTTPD_LOG_T “HTTP_LOG”;

=== Skip: SELinux modes

=== Skip: SELinux with podman containers: MCS

=== Skip: Udica

=== Multi Level Security MLS: slides #92-93

Multi level security(MLS)

Figure of read down and no write up

Type enforcement allow rule must be present before SELinux considers sensitivity level

