:time_estimate: 5

= Lab: Check Confined and Unconfined Processes in RHEL

_Estimated reading time: *{time_estimate} minutes*._

// How to break activities between "reading policies" and "the Red Hat way on RHEL"?
// Maybe I should reverse the order of presentations?

Objective::

Verify that system services run as confined processes but processes from interactive sessions run unconfined.

WARNING: Work In Progress

== Before you Start

You need a RHEL machine to which you have the root password or unrestricted sudo.

// and access to Red Hat Enterprise Linux package repositories, to install any missing packages.

// You also need internet access to download sample applications and scripts from GitHub.

These instructions were tested on RHEL 9.3 but should work with minimal change on older releases (since RHEL 7) and newer releases.

== Instructions

1. First check that unprivileged users and their processes are unconfined.
+
1.1.
Open a terminal to your RHEL machine and login with an unprivileged user. In my example, the username is `student` but the actual username and user id doesn't matter, as long as it is not root.
+
[source,subs="verbatim,quotes"]
--
$ *whoami*
student
$ *id*
uid=1000(student) gid=1000(student) groups=1000(student),10(wheel) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
--
You can tell the user is unconfined from the type field in the SELinux context of the user, which is `unconfind_t`.
+
1.2. Verify that processes created by unprivileged users are unconfined:
+
[source,subs="verbatim,quotes"]
--
$ *ps -Z*
LABEL                               PID TTY          TIME CMD
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 1128 pts/0 00:00:00 bash
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 1275 pts/0 00:00:00 ps
--
+
Remember that most commands in Bash, including the `ps` command, create new processes.

2. Check that files created by unprivileged users are NOT unconfined.
+
2.1. Verify the context on the user's home directory:
+
[source,subs="verbatim,quotes"]
--
$ *ls -dZ $HOME*
unconfined_u:object_r:user_home_dir_t:s0 /home/student
--
+
2.2. Create a file and verify it gets the same context as the user's home directory:
+
[source,subs="verbatim,quotes"]
--
$ *touch $HOME/test.empty*
$ *ls -dZ $HOME/test.empty*
unconfined_u:object_r:user_home_t:s0 /home/student/test.empty
--

3. Change the context of the file (requires root privileges) and see that the user cannot access the file anymore, despite being the owner and having POSIX permissions on it.
+
3.1. First, find a file type for something a regular user shouldn't have access to:
+
[source,subs="verbatim,quotes"]
--
$ *ls -Z /etc/shadow*
system_u:object_r:shadow_t:s0 /etc/shadow
--
+
3.2. Change the type of the file `test.empty`:
+
[source,subs="verbatim,quotes"]
--
$ sudo chcon -t shadow_t $HOME/test.empty
$ ls -lZ  $HOME/test.empty
-rw-r--r--. 1 student student unconfined_u:object_r:shadow_t:s0 0 Jul 12 15:09 /home/student/test.empty
--
+
3.3. Surprise! The unconfined process can write to the file!
+
[source,subs="verbatim,quotes"]
--
$ echo '123' > $HOME/test.empty
$ cat $HOME/test.empty
123
--

4. So, how does unconfined user get access to their files? The `sesearch` and `seinfo` commands can show that information.
+
4.1. Install the the `setools-console` package:
+
[source,subs="verbatim,quotes"]
--
$ sudo install -y setools-console
...
Complete!
--
+
4.2. Show the rule that enables unconfined access to everything

5. Show that a system service cannot access user files with runcon and sesearch. Contrast services which do need access to user files (crond, httpd) with services which do not (mysqld)

6. Show a domain type transition? [CHECK WHEN TO SWITCH FROM PROCESS TO DOMAIN]


This concludes the activity.

The next section TBD


== FROM HERE ON, RAW COPY-AND-PASTE FROM OTHER SOURCES, PENDING REORGANIZATION

https://redhatgov.io/workshops/selinux_policy/exercise1.2/ 
